version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - 8005:8000
    env_file:
      - docker/dev/env/.env
      - docker/.env.accounts
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12.0-alpine
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/dev/env/.env.db

  jupyter_notebook:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    command: python manage.py shell_plus --notebook
    depends_on:
      - web
    ports:
    - 8888:8888
    env_file:
      - docker/dev/env/.env
volumes:
  postgres_data:
