# Generated by Django 3.1.1 on 2020-09-21 08:30

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.conf import settings


def set_superuser(apps, schema_editor):
    user_obj = apps.get_model("authentificate", "User")
    user = user_obj(
        id=1,
        username='Nikolay',
        email='samsonov@gmail.com',
        first_name='Nikolay',
        last_name='Samsonov',
        is_staff=True,
        is_active=True,
        is_superuser=True,
    )
    user.password = make_password('password')
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentificate', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_superuser),
    ]
